run:
  deadline: 240s
  tests: false
  skip-dirs:
    - vendor

linters-settings:
  dupl:
    threshold: 110
  lll:
    line-length: 128

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - maligned
    - golint
    - interfacer
    - scopelint
    - godox
    - gofumpt
    - gci

issues:
  exclude-rules:
    # Exclude lll issues for long lines with go:generate for testing
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - promlinter
        - gomnd
      path: "pkg/"